---
language: ruby
script: bundle exec rspec
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then exit 0; fi
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku plugins:install https://github.com/ddollar/heroku-anvil
- heroku build -r minefold-help -b https://github.com/heroku/heroku-buildpack-ruby.git

env:
  global:
  - secure: ! 'erPSj+PQ2NNPSUt/goJjL20JsRV9grfCTb5uNmGFdtr+zfCe8Zau74ZFu0CY
      NY4Y+V7vFJTlkeBY6DvguBQ88eq3MGmMNo83ebJ9rKSa6WAmydGku3owVotD
      0TigQc4I/3hpx/KbrSZbC8FkHhpzK3FGlsDrFChvcJodoixkLGk='
